apiVersion: v1
kind: Namespace
metadata:
  name: rw-automotive
  labels:
    name: rw-automotive
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rw-automotive-quota
  namespace: rw-automotive
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    persistentvolumeclaims: "5"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: rw-automotive-limits
  namespace: rw-automotive
spec:
  limits:
  - max:
      cpu: "2"
      memory: "2Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
