version: '3.8'

services:
  # RW Automotive Website
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rw-automotive-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - rw-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rw-network:
    driver: bridge

# Optional: Add volumes for persistent data if needed
# volumes:
#   app-data:
